name: Awesome App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: https://margaiwangara.me/awesome-app/
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
